### ISSUE TITLE
Clear user Id filter

### ISSUE THREAD

**Issue by albertotn** [smartcommunitylab/smartcampus.gamification#109]
1) open players list:

![screen shot 2016-08-18 at 12 28 05](https://cloud.githubusercontent.com/assets/12526457/17770670/41347cf4-653f-11e6-890f-01f93dc8bb8e.png)

2) filter using playerId 1

![screen shot 2016-08-18 at 12 28 39](https://cloud.githubusercontent.com/assets/12526457/17770678/4f910b8c-653f-11e6-9a9d-4e89e9343a2d.png)

3) go back to games list

![screen shot 2016-08-18 at 12 29 07](https://cloud.githubusercontent.com/assets/12526457/17770686/6026380a-653f-11e6-88c9-118fb36a78cf.png)

4) players list is still filtered, need to refresh in order to get full players list

![screen shot 2016-08-18 at 12 29 44](https://cloud.githubusercontent.com/assets/12526457/17770695/74559596-653f-11e6-9136-74ce252eab7d.png)

If it is a feature, it's better (IMHO) to preserve playerId into filter, or reload all players list

**Comment by mirkoperillo** [comment]
fixed by 05129157f8fe8004b65cf8987a7005bc1f965368
