### ISSUE TITLE
Report on incremental classifications

### ISSUE THREAD

**Issue by mirkoperillo** [smartcommunitylab/smartcampus.gamification#115]
produce a report about incremental classifications.

Add possibility to load some player records to bind with playerId and use it in report and generally in the engine

**Comment by kazhamiakin** [comment]
To be implemented externally

**Comment by kazhamiakin** [comment]
Should be implemented in the "mobile console"

**Comment by mirkoperillo** [comment]
I close the issue, please reopen it if necessary
