### ISSUE TITLE
challenge generator: reset weekly counters

### ISSUE THREAD

**Issue by mirkoperillo** [smartcommunitylab/smartcampus.gamification#54]
When generator push challenge custom data to player state, it must reset weekly counters

**Comment by nyhobbit** [comment]
we need to agree on convention to name all of below
- weekly counters (Km and trips, for each mode)
- global counters (same as above)

**Comment by albertotn** [comment]
(with @nyhobbit ) Pull request #66 provides reset rules for counters but we need to be able to do same thing through a weekly task

**Comment by mirkoperillo** [comment]
In a previous meeting we decided that the challenge generator has to reset the counters when it pushes challenge customdata in player state

**Comment by albertotn** [comment]
I confirm, reset during challenge upload see https://github.com/das-fbk/game-engine.challenge-gen
