### ISSUE TITLE
Undeletable rule

### ISSUE THREAD

**Issue by albertotn** [smartcommunitylab/smartcampus.gamification#70]
Using this test:

https://github.com/nyhobbit/smartcampus.gamification/blob/long-game/game-engine.challenge-gen/src/test/java/eu/trentorise/challenge/rest/RestTest.java#L44

It's possible to enter using REST Api a rule that from user console can be deleted but after a restart or a refresh come back.

I think could be because rule is not correct in some ways ?

**Comment by mirkoperillo** [comment]
I tried to reproduce the bug running `gameReadGameStateTest` as illustrated.
No new rule is created, so I'm not be able to reproduce the issue.
I consider the issue closed, reopen it with more information and a reproducible test.
