### ISSUE TITLE
Not possibile to modify a rule

### ISSUE THREAD

**Issue by albertotn** [smartcommunitylab/smartcampus.gamification#73]
After last commits on branch long-game is not possible to modify an already inserted rule.

Test case:
1) create a rule from interface
2) try to modify it
3) return error as screenshoot below:

![modifyerrorrule](https://cloud.githubusercontent.com/assets/12526457/14351033/3f9d6002-fccd-11e5-9e5d-e5dd199c1067.png)

**Comment by mirkoperillo** [comment]
Reproduced..this is a bug
