### ISSUE TITLE
Ridurre dimensione icona e notifica di caricamento

### ISSUE THREAD

**Issue by albertotn** [smartcommunitylab/smartcampus.gamification#77]
Durante il caricamento della classifica si presenta un immagine che mostra il caricamento e la relativa descrizione:

![screenshot_2016-04-21-10-59-56](https://cloud.githubusercontent.com/assets/12526457/14704551/893e098a-07b5-11e6-99d5-6c9ed9fe066d.png)

A mio avviso sarebbe meglio ridurre la dimensione dell'immagine e del testo, perché pari alla dimensione del titolo della pagina

**Comment by regolo85** [comment]
Created icon and text for mobile view
