### ISSUE TITLE
Ridimensionamento pagina durante la registrazione

### ISSUE THREAD

**Issue by albertotn** [smartcommunitylab/smartcampus.gamification#78]
Durante una registrazione é possibile ridimensionare il pannello modale che mostra le informazioni relative, "tagliando" di fatto la descrizione:

![screenshot_2016-04-21-11-03-07](https://cloud.githubusercontent.com/assets/12526457/14704593/c1f55f4e-07b5-11e6-8493-5f180a07a6b9.png)

Questo é in parte un problema perché se si completa la registrazione o si torna indietro, la pagina che mostra il gioco é parzialmente ridimensionata:

![screenshot_2016-04-21-11-10-20](https://cloud.githubusercontent.com/assets/12526457/14704612/de39fd86-07b5-11e6-9cdd-f3f324c6411a.png)

**Comment by regolo85** [comment]
Problema risolto. Aggiunta proprietà alla pagina html che blocca il ridimensionamento del modale da parte dell'utente.
