### ISSUE TITLE
Game filtering enhancements

### ISSUE THREAD

**Issue by albertotn** [smartcommunitylab/smartcampus.gamification#79]
In game monitor page:

![game filtering](https://cloud.githubusercontent.com/assets/12526457/14704855/0b113184-07b7-11e6-8d1f-590c59a74c57.png)

could be useful to:

1) have game id somewhere
2) default focus on ID player filtering for quick filtering
3) if user write player ID and press enter, start filtering
4) an order, for example alphabetical on player name

**Comment by mirkoperillo** [comment]
1) fix on 7982dd07c15ae51a791c967e75c23bb6dee0908c
3) fix on b6766c61f48e6848eaae3ed42652f1896a539ff1

**Comment by mirkoperillo** [comment]
2) fix on e515964e6854990833bf65731d35707c29ce704a

**Comment by kazhamiakin** [comment]
No ordering on player name as no name exists. In future, consider extended user profile internally?
