### ISSUE TITLE
Error on add a new point concept

### ISSUE THREAD

**Issue by albertotn** [smartcommunitylab/smartcampus.gamification#84]
In gamification console, if user try to add a new points concept with name with a white space as first character, results in an error as following:

![erroredev inserimento points concept](https://cloud.githubusercontent.com/assets/12526457/15009304/f3531222-11e5-11e6-8650-0ad3de51f495.png)

**Comment by mirkoperillo** [comment]
I test it and this behavior doesn't occur.

When I create a point concept with a name starting with a white space, the space is correctly trimmed
