### ISSUE TITLE
Case-insensitive check for recommendations

### ISSUE THREAD

**Issue by nyhobbit** [smartcommunitylab/smartcampus.gamification#85]
The check against the mongo-stored nick of a Player, to evaluate whether that Player has recommended the game to another player who is registering, should be made case-insensitive, to avoid cases in which recommendations are discarded because of capitalization settings in the  mobile phone or similar.
We are missing some recommendations done in good faith for that,

**Comment by mirkoperillo** [comment]
actually in testing

**Comment by regolo85** [comment]
Corrected bug. Now a recommendation is done with a case-insensitive player nickname and the system is able to manage it correctly.
