### ISSUE TITLE
check on date/time selection

### ISSUE THREAD

**Issue by LucaMora** [smartcommunitylab/smartcampus.gamification#92]
check and validate date/time when editing or creating a game because now is possible to select a date in the past and an invalid hour

**Comment by mirkoperillo** [comment]
Maintain possibility to set a date in the past.

Correct to check if date fields are valid.

**Comment by LucaMora** [comment]
fixed in ea420f4104f60bcec330d61d37a0da8cebedaffe

**Comment by mirkoperillo** [comment]
merged on branch r2.0.0
